---
subtitle: "Philosophy of Law: Stetson University, Phil 284"
title: "<font style='font-size:1em;'>🗓️ Critical Legal Studies; Juncan Kennedy</font>"
author: Prof. [Reynolds](#)
institute: '[Stetson University](#)'
date: 02 September 2026
date-meta: 14 March 2023
date-format: "DD MMM YYYY"
toc: false
toc-depth: 1
toc-title: "CLS"
center-title-slide: false
from: markdown+emoji
format:
  revealjs:
    theme: moon
    fig-responsive: true
    slide-number: true
    incremental: true
    mouse-wheel: false
    auto-play-media: true
    preview-links: auto
    logo: /figures/icons/course_favicon.png
    css: /css/styles_slides.css
footer: 'Philosophy of Law: Stetson University 284'
---

CLS scholars try to establish the illegitimacy of the legal order by debunking law's pretensions to determinacy, neutrality, and objectivity.

Shaped by:

* Marxist
* Realist tradition
* Deconstruction
* Feminism
* Environmentalism
* Anti-racism

---

::: {.r-fit-text}

The central attack of CLS is formalism:

> "the idea that there is an autonomous and neutral mode of 'legal' reasoning and rationality through which legal specialists apply doctrine in concrete cases to reach results that are independent of the specialists' ethical ideals and political purposes." [J. Paul Oetken: Form and Substance in Critical Legal Studies, p. 2211]

Cls argues that instead law is indeterminate:  legal rules and arguments fail to compel or justify definite answers in legal disputes.

> A primary concern of CLS is to demonstrate how language and other formal structures are used in subtle, unconscious ways to channel our thought into dominant patterns, to mystify us. [J. Paul Oetken: Form and Substance in Critical Legal Studies, p. 2213]

:::

---

# Rhetorical Modes and Substantive Issues in the Law

What is the nature and interconnection of the different rhetorical modes found in American private law opinions, articles, and treatises?

* Formal dimensions of rules and standards
* Substantive dimensions of individualism and altruism

## Two modes for dealing with questions of the form in which legal solutions to the substantive problems:

* Formal Rules: uses clearly defined, highly administrable, general rules
* Informal Standards: uses equitable standards that produce ad hoc decisions with little precedential (precedent) value.

---

::: {.r-fit-text}

As Such:

1. Altruist views on substantive private law issues lead to willingness to resort to standards in administration.
2. Individualism harmonizes with an insistence on rigid rules rigidly applied (formal modes).
3. Substantive and formal conflict in private law and cannot be reduced to disagreement about how to apply some neutral calculus that will "maximize the total satisfactions of valid human wants".
4. Therefore, we are divided among ourselves and also within ourselves between irreconcilable visions of humanity and society, and between radically different aspirations for our common future.

:::

---

### Sections I and II

::: {.r-fit-text}

1. Jurisprudence of Rules
   1. Dimensions of Form
   2. Relationships between formal dimensions
2. Types of relationships between form and substance
   1. Contextualization
   2. Form as Substance
   3. Altruism and Individualism
* Problem of choice between rules and standards as the form for legal directives.
* Collecting and organizing the wide variety of arguments that have been found persuasive in different areas of legal study.

:::

---

### Sections III and IV

* Develops a dichotomy of individualism and altruism
* Hopes to bring a measure of order to the chaotic mass of "policies" lawyers
* Policies can be used in justifying particular legal rules.

---

### Sections V, VI, and VII

* Argues that the formal and substantive dichotomies are in fact aspects of a single conflict.
* Whose history is briefly traced through a hundred and fifty years of dispute
* Including moral, economic, and political.

---

### Section VIII

Outlines the contradictory sets of fundamental premises that underlie this conflict.

---

### Section IX

Conclusion

# Section I: The Jurisprudence of Rules

---

(A) "Three" Dimensions for Describing Legal directives:

::: {.r-fit-text}

1. Formal Realizability vs. Standards, principles, policies: The quality of "ruleness" in a legal directive vs. substantive objectives
2. Generality vs. particularity, e.g., rule setting age of legal majority at 21 vs. rule setting age of capacity to contract at 21.
   1. Particularity - Rules: A directive that requires response
   2. Particularity - Standards, principle or policy: substantive objective of legal order. E.g., good faith, due care, fairness
   3. Generality - wide scope intended to deal with many different fact situations
   4. General rule over or under inclusive, than particular; multiplication of particular rules undermines their realizability (too many questions); general rules should reduce judicial lawmaking; application of standard to fact produces narrow rule.
3. Formalities vs. rules designed to deter harmful behavior
   1. Sanctions: Institutions designed to prevent morally wrong or unwanted behaviors
   2. Formalities: Institutions designed to facilitate legal ordering "In every case, the formality means that unless the parties adopt the prescribed mode of manifesting their wishes, they will be ignored."
   3. How do we apply the two concepts?

:::

---

(B) Relationship between Formal Dimensions (rules as formalities)

::: {.r-fit-text}

1. Directives to deter wrongdoing
   1. Rules vs Standards: Mechanical vs. biased arbitrariness
   2. Rules: standards deter both desirable and undesirable conduct
   3. Standards can be paper tigers
   4. Rules can alert to potential danger of sanction
2. Formalities: general rules can be over and under inclusive
   1. Casting formalities as rules: "the application of the rule should only very rarely lead to the nullification of the intent of the parties."
   2. Critique of the argument for rules, two assumptions: " If the argument for rules is to work, we must anticipate that private parties will in fact respond to the threat of the sanction of nullity by learning to operate the system."; " that legal directives that looked general and formally realizable were in fact indeterminate."

:::

---

* Extreme, formally recognizable rule: directive to an official that requires him to respond to presence together or each of a list of easily distinguishable factual aspects of a situation by intervening in a determinate way.
* Standard or principle or policy: E.g., good faith, due care, fairness, unconscionably, unjust enrichment, and reasonableness.

