---
title: "Law, Spring 2026"
format:
  html:
    include-before-body: helpers/remove-nav.html
    include-after-body: helpers/remove-title.html
---

<a href="./2026_logic/index.qmd">
    <button class="button-61">Click Here for Law, Spring 2026</button>
</a>

In general, philosophy requires one to apply principles of reasoning to different philosophical issues. Accordingly, one of my goals in this course is to help you improve your critical reasoning skills. These skills are useful not only with respect to this class, but to other philosophy and law classes as well. A second goal of mine is to teach you some of the fundamental philosophical ideas behind much of that which we call law. We will examine theories which attempt to provide answers to such questions as: What is a law? What makes a law valid or binding? Does one always have a moral obligation to obey the law? What gives society the right to punish people whose actions are harmful only to the individual, him/herself (paternalism)? Does society have the right to harm those who break the law (criminal punishment)? Should attempted crimes be punished less severely than completed crimes? We will not spend much time discussing specific public policy issues such as: Whether raising the drinking age saves lives, whether smoking marijuana is a victimless crime (whether it harms others), or whether the death penalty is a deterrent. We will not discuss what the law is; instead, we will discuss what the law ought to be.

### 📑 Course Brief

**Focus:**

1. Developing critical reasoning skills.
2. Discovering some of the fundamental philosophical ideas in law.

**How:** hands-on learning

### 🎯 Learning Objectives

* What is a law?
* What makes a law valid or binding?
* Do we have a moral obligation to obey the law?
* What gives society the right to punish people whose actions are harmful only to the individual, him/herself (paternalism)?
* Does society have the right to harm those who break the law (criminal punishment)?
* Should attempted crimes be punished less severely than completed crimes?

### What is not covered

Public policy issues such as:

* Whether raising the drinking age saves lives
* Wehther smoking marijuana is a victimless crime (whether it harms others)
* Whether the death penalty is a deterrent.

We do not discuss what the law is; instead, we will discuss what the law ought to be.
