---
title: "🗓️ Fuller, Speluncean Cave"
---

| Day | Date | Discussion |
| --- | --- | --- |
|  |  | **Syllabus (Subject to Modification)** |
| Thursday | January 15 | Fuller, "The Case of the Speluncean Explorers" (Handout - Canvas) |

## 👨‍🏫 Lecture Slides

Either click on the slide area below or click [here](slides.qmd) to view it in fullscreen.

Download the reading [here:](../../../readings/1_Fuller-CaseSpelunceanExplorers-1949.pdf)


<div class="container" style="position: relative;overflow: hidden;width: 100%;min-height:600px;">
<iframe src="https://eclass.uoa.gr/modules/document/file.php/PPP641/%CE%95%CE%BD%CF%8C%CF%84%CE%B7%CF%84%CE%B1%208%CE%B7%3A%20%CE%A6%CE%AC%CE%BA%CE%B5%CE%BB%CE%BF%CF%82%20%CE%9C%CE%B1%CE%B8%CE%AE%CE%BC%CE%B1%CF%84%CE%BF%CF%82/Fuller_The%20Case%20of%20the%20Speluncean%20Explorers.pdf" style="position=absolute;top: 0;left: 0;bottom: 0;right: 0;width: 100%;min-height:600px;"></iframe>
</div>

Use your keypad to navigate the slides.

<div class="container" style="position: relative;overflow: hidden;width: 100%;min-height:600px;">
<iframe src="slides.html" style="position=absolute;top: 0;left: 0;bottom: 0;right: 0;width: 100%;min-height:600px;"></iframe>
</div>

🎥 Looking for lecture recordings? You can find them on Canvas.

## ✍️ Coursework

🚧 Come back after the lecture to read the coursework instructions for the week 🚧


## 📚 Recommended Reading

- [Click here to access the reading material](../../../readings/1_Fuller-CaseSpelunceanExplorers-1949.pdf)

- Check the end of slides for the list of references cited in the lecture.

## 📟 Communication

- If you feel like it, introduce your 'selves' in the `#introductions` channel in [Discussions](https://stetson.instructure.com/courses/38093/discussion_topics/162462)
